spark-operator:  # This section controls the behavior of the spark operator sub-chart
  sparkJobNamespace: spark-apps
  image:
    repository: ghcr.io/googlecloudplatform/spark-operator
    tag: v1beta2-1.3.4-3.1.1
    pullPolicy: IfNotPresent
  imagePullSecrets: []

  # Required on EKS if the cluster has a custom CNI (e.g. Calico),
  # then the control plane (managed by AWS) can't communicate with
  # pods' IP CIDR and webhooks don't work.
  hostNetwork: false

  webhook:
    enable: true
    # If hostNetwork is set to true it is probably a good idea to change this (e.g. 25554)
    port: 443

  serviceAccounts:
    spark:
      create: false  # We create it ourselves so that we can add image pull secrets (static part)

  resources:
    requests:
      cpu: 200m
      memory: 50Mi

  rbac:
    createClusterRole: true  # This one is part of the blue/green
    createRole: false        # This one is static

  podLabels:
    bigdata.spot.io/component: "spark-operator"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: spotinst.io/node-lifecycle
            operator: In
            values:
            - od
          - key: spotinst.io/ocean-vng-id
            operator: Exists
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: bigdata.spot.io/component
              operator: Exists
          topologyKey: "kubernetes.io/hostname"
