---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigdata-operator.fullname" . }}-metrics
  labels:
  {{- include "bigdata-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
  {{- include "bigdata-operator.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
